const {chromium}=require(process.argv[2]||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
process.chdir(path.resolve(__dirname,'..'));
fs.mkdirSync('reports',{recursive:true});
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 try{
  const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
  p.on('pageerror',e=>errors.push(e.message));
  await p.route('https://fonts.googleapis.com/**',route=>route.abort());
  await p.goto('http://127.0.0.1:5173',{waitUntil:'domcontentloaded'});
  await p.getByRole('heading',{name:/Good ideas deserve/}).waitFor();
  await p.screenshot({path:'reports/redesign-home.png',fullPage:true});
  await p.getByRole('link',{name:'Explore examples →'}).click();
  await p.getByRole('heading',{name:'Try it. Make it yours.'}).waitFor();
  await p.getByRole('link',{name:'Use this example ↗'}).first().click();
  await p.locator('.upload-preview').waitFor();
  await p.getByLabel('Project name',{exact:true}).fill('Editor regression');
  await p.getByRole('button',{name:'Create project →',exact:true}).click();
  await p.getByLabel('Selected element',{exact:true}).waitFor({timeout:120000});
  async function ready(){await p.getByRole('status').filter({hasText:'Preview and exports up to date'}).waitFor();}
  await ready();
  const editorUrl=p.url();
  await p.getByRole('button',{name:'Select button Sign in',exact:true}).click();
  await p.getByLabel('Element text',{exact:true}).fill('Launch now');
  await p.getByLabel('Fill color',{exact:true}).fill('#335577');
  await ready();
  await p.frameLocator('iframe').getByRole('button',{name:'Launch now',exact:true}).waitFor();
  await p.getByRole('button',{name:'Duplicate',exact:true}).click();await ready();
  assert.equal(await p.frameLocator('iframe').getByRole('button',{name:'Launch now',exact:true}).count(),2);
  await p.getByRole('button',{name:'Delete',exact:true}).click();await ready();
  assert.equal(await p.frameLocator('iframe').getByRole('button',{name:'Launch now',exact:true}).count(),1);
  await p.getByRole('button',{name:'Undo',exact:true}).click();await ready();
  assert.equal(await p.frameLocator('iframe').getByRole('button',{name:'Launch now',exact:true}).count(),2);
  await p.getByRole('button',{name:'Redo',exact:true}).click();await ready();
  await p.getByRole('button',{name:'Select button Launch now',exact:true}).click();
  const before=Number(await p.getByLabel('X position',{exact:true}).inputValue());
  const hit=await p.getByRole('button',{name:'Select button Launch now',exact:true}).boundingBox();
  await p.mouse.move(hit.x+hit.width/2,hit.y+hit.height/2);await p.mouse.down();await p.mouse.move(hit.x+hit.width/2+25,hit.y+hit.height/2+10,{steps:5});await p.mouse.up();await ready();
  assert(Number(await p.getByLabel('X position',{exact:true}).inputValue())>before);
  await p.getByRole('button',{name:'Undo',exact:true}).click();await ready();
  assert.equal(Number(await p.getByLabel('X position',{exact:true}).inputValue()),before);
  const initialWidth=Number(await p.getByLabel('Width',{exact:true}).inputValue());
  const handle=await p.getByRole('button',{name:'Resize selected element',exact:true}).boundingBox();
  await p.mouse.move(handle.x+5,handle.y+5);await p.mouse.down();await p.mouse.move(handle.x+30,handle.y+15,{steps:5});await p.mouse.up();await ready();
  assert(Number(await p.getByLabel('Width',{exact:true}).inputValue())>initialWidth);
  await p.getByRole('button',{name:'Undo',exact:true}).click();await ready();
  await p.getByRole('button',{name:'Zoom in',exact:true}).click();
  await p.getByRole('button',{name:'Fit',exact:true}).click();
  await p.screenshot({path:'reports/redesign-editor.png',fullPage:true});
  for(const [name,file] of [['↓ HTML / CSS','redesign-html.zip'],['↓ React project','redesign-react.zip']]){
   await p.getByRole('button',{name:'Export ↓',exact:true}).click();const event=p.waitForEvent('download');await p.getByRole('button',{name,exact:true}).click();await(await event).saveAs(path.resolve('reports',file));
  }
  await p.getByRole('button',{name:'← Projects',exact:true}).click();
  await p.getByRole('heading',{name:'Editor regression',exact:true}).waitFor();
  await p.getByRole('button',{name:'Rename',exact:true}).click();
  await p.getByLabel('Project name',{exact:true}).fill('Saved regression');
  await p.getByRole('button',{name:'Save',exact:true}).click();
  await p.getByRole('heading',{name:'Saved regression',exact:true}).waitFor();
  await p.screenshot({path:'reports/redesign-projects.png',fullPage:true});
  await p.reload({waitUntil:'domcontentloaded'});
  await p.getByRole('heading',{name:'Saved regression',exact:true}).waitFor();
  await p.getByRole('heading',{name:'Saved regression',exact:true}).click();await ready();
  await p.frameLocator('iframe').getByRole('button',{name:'Launch now',exact:true}).waitFor();
  await p.getByRole('button',{name:'Select button Launch now',exact:true}).click();
  await p.getByRole('button',{name:'Reset',exact:true}).click();await ready();
  await p.frameLocator('iframe').getByRole('button',{name:'Sign in',exact:true}).waitFor();
  await p.setViewportSize({width:390,height:844});
  await p.screenshot({path:'reports/redesign-mobile-editor.png',fullPage:true});
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await p.getByRole('button',{name:'← Projects',exact:true}).click();
  await p.getByRole('link',{name:'Help',exact:true}).click();
  await p.getByText('Where are my projects saved?',{exact:false}).click();
  assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await p.goto(editorUrl,{waitUntil:'domcontentloaded'});await ready();
  await p.getByRole('button',{name:'← Projects',exact:true}).click();
  p.once('dialog',d=>d.accept());
  await p.getByRole('button',{name:'Delete',exact:true}).click();
  await p.getByRole('heading',{name:'A fresh canvas for your ideas.'}).waitFor();
  assert.deepEqual(errors,[]);
  console.log('PASS: pages, examples, creation, edits, duplicate/delete, undo/redo, drag/resize, zoom, exports, persistence/reload, rename/reset, mobile, project deletion');
 }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exit(1);});
