const {chromium}=require(process.argv[2]||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});try{
 const p=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:5173/new?example=rounded');
 await p.locator('.upload-preview').waitFor();await p.getByRole('button',{name:'Create project →',exact:true}).click();
 const ready=()=>p.getByRole('status').filter({hasText:'Preview and exports up to date'}).waitFor({timeout:120000});
 await ready();
 await p.getByRole('button',{name:'Add text',exact:true}).click();await ready();
 await p.getByLabel('Element text',{exact:true}).fill('Portable project');await ready();
 await p.getByRole('button',{name:'Align center horizontally',exact:true}).click();await ready();
 assert.equal(Number(await p.getByLabel('X position',{exact:true}).inputValue()),350);
 await p.getByRole('button',{name:'Align top',exact:true}).click();await ready();
 assert.equal(await p.getByLabel('Y position',{exact:true}).inputValue(),'0');
 await p.getByRole('button',{name:'Select text Portable project',exact:true}).focus();
 await p.keyboard.press('ArrowRight');await ready();
 assert.equal(Number(await p.getByLabel('X position',{exact:true}).inputValue()),351);
 await p.keyboard.press('Shift+ArrowDown');await ready();
 assert.equal(Number(await p.getByLabel('Y position',{exact:true}).inputValue()),10);
 await p.getByRole('button',{name:'Undo',exact:true}).click();await ready();
 assert.equal(Number(await p.getByLabel('Y position',{exact:true}).inputValue()),0);
 await p.getByRole('checkbox',{name:'Snap to 8 px grid',exact:true}).check();
 const hit=await p.getByRole('button',{name:'Select text Portable project',exact:true}).boundingBox();
 await p.mouse.move(hit.x+hit.width/2,hit.y+hit.height/2);await p.mouse.down();await p.mouse.move(hit.x+hit.width/2+19,hit.y+hit.height/2+26,{steps:5});await p.mouse.up();await ready();
 assert.equal(Number(await p.getByLabel('X position',{exact:true}).inputValue())%8,0);
 assert.equal(Number(await p.getByLabel('Y position',{exact:true}).inputValue())%8,0);
 await p.getByRole('button',{name:'Export ↓',exact:true}).click();const event=p.waitForEvent('download');await p.getByRole('button',{name:'↓ Project backup',exact:true}).click();
 const backupFile=path.resolve('reports/roundtrip.screenweave.json');await(await event).saveAs(backupFile);
 const backup=JSON.parse(fs.readFileSync(backupFile,'utf8'));
 const originalUrl=p.url();
 await p.getByRole('button',{name:'← Projects',exact:true}).click();
 await p.locator('input[aria-label="Project backup to import"]').setInputFiles(backupFile);
 await p.getByRole('status').filter({hasText:'Project imported as a new copy.'}).waitFor();
 assert.equal(await p.locator('.project-card').count(),2);
 await p.locator('.project-card').first().locator('h3').click();await ready();assert.notEqual(p.url(),originalUrl);
 await p.frameLocator('iframe').getByText('Portable project',{exact:true}).waitFor();
 await p.setViewportSize({width:390,height:844});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await p.screenshot({path:'reports/backup-alignment-mobile.png',fullPage:true});
 await p.getByRole('button',{name:'← Projects',exact:true}).click();
 await p.locator('input[aria-label="Project backup to import"]').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from('{"format":"other"}')});
 await p.getByRole('alert').filter({hasText:'Choose a ScreenWeave'}).waitFor();assert.equal(await p.locator('.project-card').count(),2);
 const malformed=structuredClone(backup);malformed.project.layout.elements[0].width=-1;
 await p.locator('input[aria-label="Project backup to import"]').setInputFiles({name:'invalid-layout.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(malformed))});
 await p.getByRole('alert').filter({hasText:'Invalid element dimensions'}).waitFor();assert.equal(await p.locator('.project-card').count(),2);
 assert.deepEqual(errors,[]);console.log('PASS: backup round trip, import copy, malformed imports, alignment, keyboard nudges, snap, undo, mobile.');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
