import {useEffect,useRef,useState,type PointerEvent} from 'react';
import {ElementEditor,type Element,type Layout} from './ElementEditor';
import {apiRequest,navigate,saveProject,type Project,type Result} from './projects';
export default function Editor({project}:{project:Project}){
 const [draft,setDraft]=useState(project.layout),[selected,setSelected]=useState(project.layout.elements[0]?.id||'');
 const [past,setPast]=useState<Layout[]>([]),[future,setFuture]=useState<Layout[]>([]);
 const [result,setResult]=useState<Result|null>(null),[pending,setPending]=useState(true),[error,setError]=useState(''),[saveError,setSaveError]=useState(''),[saved,setSaved]=useState(true),[retry,setRetry]=useState(0);
 const [tab,setTab]=useState<'preview'|'html'|'css'>('preview'),[zoom,setZoom]=useState<number|null>(null),[reference,setReference]=useState(false),[size,setSize]=useState({width:800,height:650});
 const [motion,setMotion]=useState<Element|null>(null);
 const canvas=useRef<HTMLDivElement>(null),version=useRef(0),saveChain=useRef(Promise.resolve());
 const gesture=useRef<{element:Element;x:number;y:number;resize:boolean}|null>(null);
 const chosen=draft.elements.find(e=>e.id===selected);
 const scale=zoom??Math.min(1,Math.max(100,size.width-80)/draft.viewport.width,Math.max(100,size.height-80)/draft.viewport.height);
 useEffect(()=>{if(!canvas.current)return;const o=new ResizeObserver(([e])=>setSize({width:e.contentRect.width,height:e.contentRect.height}));o.observe(canvas.current);return()=>o.disconnect();},[tab]);
 useEffect(()=>{
  const c=new AbortController(),v=version.current;setPending(true);setError('');
  const timer=setTimeout(async()=>{try{const next=await apiRequest('/render',JSON.stringify(draft),'application/json',c.signal);if(!c.signal.aborted&&v===version.current){setResult(next);setPending(false);}}catch(e){if(!c.signal.aborted&&v===version.current){setError(e instanceof Error?e.message:'Preview failed.');setPending(false);}}},250);
  return()=>{clearTimeout(timer);c.abort();};
 },[draft,retry]);
 useEffect(()=>{let active=true;setSaved(false);saveChain.current=saveChain.current.catch(()=>{}).then(async()=>{await saveProject({...project,layout:draft,updatedAt:Date.now()});});saveChain.current.then(()=>{if(active){setSaved(true);setSaveError('');}}).catch(()=>{if(active)setSaveError('Autosave failed. Keep this page open and export your work.');});return()=>{active=false;};},[draft,project]);
 function commit(next:Layout){if(JSON.stringify(next)===JSON.stringify(draft))return;version.current++;setPending(true);setPast(p=>[...p.slice(-49),draft]);setFuture([]);setDraft(next);}
 function change(p:Partial<Element>){commit({...draft,elements:draft.elements.map(e=>e.id===selected?{...e,...p}:e)});}
 function undo(){if(!past.length)return;version.current++;setPending(true);setFuture(f=>[draft,...f]);setDraft(past[past.length-1]);setPast(p=>p.slice(0,-1));}
 function redo(){if(!future.length)return;version.current++;setPending(true);setPast(p=>[...p,draft]);setDraft(future[0]);setFuture(f=>f.slice(1));}
 function remove(){if(!selected)return;commit({...draft,elements:draft.elements.filter(e=>e.id!==selected).map(e=>e.parent_id===selected?{...e,parent_id:null}:e)});setSelected('');}
 function duplicate(){if(!chosen||draft.elements.length>=500)return;const c={...chosen,id:'copy-'+crypto.randomUUID(),x:Math.min(10000,chosen.x+16),y:Math.min(10000,chosen.y+16)};commit({...draft,elements:[...draft.elements,c]});setSelected(c.id);}
 function reset(){const original=project.original.elements.find(e=>e.id===selected);if(original)change(original);}
 useEffect(()=>{function key(e:KeyboardEvent){if((e.target as HTMLElement).closest('input,textarea,select,[contenteditable=true]'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();redo();}else if(e.key==='Delete'){e.preventDefault();remove();}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);});
 function start(e:PointerEvent<HTMLButtonElement>,element:Element,resize=false){if(e.button!==0)return;e.preventDefault();e.stopPropagation();e.currentTarget.setPointerCapture(e.pointerId);setSelected(element.id);gesture.current={element,x:e.clientX,y:e.clientY,resize};setMotion(null);}
 function move(e:PointerEvent<HTMLButtonElement>){const g=gesture.current;if(!g)return;const dx=Math.round((e.clientX-g.x)/scale),dy=Math.round((e.clientY-g.y)/scale),clamp=(n:number,min=0)=>Math.max(min,Math.min(10000,n));setMotion({...g.element,x:g.resize?g.element.x:clamp(g.element.x+dx),y:g.resize?g.element.y:clamp(g.element.y+dy),width:g.resize?clamp(g.element.width+dx,1):g.element.width,height:g.resize?clamp(g.element.height+dy,1):g.element.height});}
 function finish(){if(motion)commit({...draft,elements:draft.elements.map(e=>e.id===motion.id?motion:e)});gesture.current=null;setMotion(null);}
 function cancel(){gesture.current=null;setMotion(null);}
 function download(kind:'html'|'react'){if(!result||pending||error)return;const bytes=Uint8Array.from(atob(result.exports[kind]),c=>c.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:'application/zip'}));const a=document.createElement('a');a.href=url;a.download='screenweave-'+kind+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const srcDoc=result?.html.replace('<link rel="stylesheet" href="styles.css">',`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; form-action 'none'"><style>${result.css}</style>`);
 const handle=motion?.id===selected?motion:chosen;
 return <div className="studio">
 <div className="studio-top"><div><button className="text-button" onClick={()=>navigate('/projects')}>← Projects</button><strong>{project.name}</strong><span className="save-status">{saveError?'Not saved':saved?'Saved on this device':'Saving…'}</span></div><div className="actions"><button disabled={!result||pending||!!error} onClick={()=>download('html')}>↓ HTML / CSS</button><button className="primary" disabled={!result||pending||!!error} onClick={()=>download('react')}>↓ React project</button></div></div>
 {(error||saveError)&&<div className="error" role="alert">{error||saveError}{error&&<button onClick={()=>setRetry(r=>r+1)}>Retry preview</button>}</div>}
 <div className="studio-body"><aside className="layers"><div className="sidebar-heading"><strong>Layers</strong><span>{draft.elements.length}</span></div><p className="muted small">Select an element to refine it.</p><div className="layer-list">{draft.elements.map(e=><button key={e.id} className={selected===e.id?'active':''} onClick={()=>setSelected(e.id)}><span className="layer-icon">{e.type==='text'?'T':e.type==='image'?'▧':'▢'}</span><span>{e.text||e.type}<small>{e.type}</small></span></button>)}</div><button className="reference-toggle" onClick={()=>setReference(!reference)}>{reference?'Hide':'Show'} reference</button>{reference&&<img className="reference-image" src={project.source} alt="Original reference"/>}</aside>
 <section className="canvas-column"><div className="canvas-toolbar"><div className="actions"><button title="Undo (Ctrl/⌘ Z)" aria-label="Undo" disabled={!past.length} onClick={undo}>↶</button><button title="Redo (Ctrl/⌘ Shift Z)" aria-label="Redo" disabled={!future.length} onClick={redo}>↷</button><div className="tabs">{(['preview','html','css'] as const).map(t=><button key={t} aria-pressed={tab===t} onClick={()=>setTab(t)}>{t==='preview'?'Canvas':t.toUpperCase()}</button>)}</div></div><div className="actions zoom"><button aria-label="Zoom out" onClick={()=>setZoom(Math.max(.1,scale-.1))}>−</button><span>{Math.round(scale*100)}%</span><button aria-label="Zoom in" onClick={()=>setZoom(Math.min(2,scale+.1))}>+</button><button title="Fit screenshot to canvas" onClick={()=>setZoom(null)}>Fit</button></div></div>
 {tab==='preview'?<div className="canvas" ref={canvas}><div className="artboard-holder" style={{minWidth:draft.viewport.width*scale+80,minHeight:draft.viewport.height*scale+80}}><div className="artboard" style={{width:draft.viewport.width*scale,height:draft.viewport.height*scale}}><iframe title="Reconstructed website" sandbox="" srcDoc={srcDoc} style={{width:draft.viewport.width,height:draft.viewport.height,transform:`scale(${scale})`}}/>{draft.elements.map(element=>{const e=motion?.id===element.id?motion:element;return <button key={e.id} className={`element-hit ${selected===e.id?'selected':''}`} aria-label={`Select ${e.type} ${e.text||e.id}`} onClick={()=>setSelected(e.id)} onPointerDown={event=>start(event,element)} onPointerMove={move} onPointerUp={finish} onPointerCancel={cancel} style={{left:e.x*scale,top:e.y*scale,width:e.width*scale,height:e.height*scale}}/>;})}{handle&&<button className="resize-handle" aria-label="Resize selected element" style={{left:(handle.x+handle.width)*scale-5,top:(handle.y+handle.height)*scale-5}} onPointerDown={e=>start(e,chosen!,true)} onPointerMove={move} onPointerUp={finish} onPointerCancel={cancel}/>}</div></div></div>:<pre className="studio-code"><code>{result?(tab==='html'?result.html:result.css):'Generating code…'}</code></pre>}
 <div className="canvas-status" role="status"><span className={pending?'dot working':'dot'}/>{pending?'Updating preview and exports…':error?'Preview unavailable':'Preview and exports up to date'}<span>{draft.viewport.width} × {draft.viewport.height}</span></div></section>
 <aside className="properties"><div className="sidebar-heading"><strong>Properties</strong><span>{chosen?.type||'Nothing selected'}</span></div><div className="element-actions"><button disabled={!chosen||draft.elements.length>=500} onClick={duplicate}>Duplicate</button><button disabled={!project.original.elements.some(e=>e.id===selected)} onClick={reset}>Reset</button><button className="danger" disabled={!chosen} onClick={remove}>Delete</button></div><ElementEditor layout={draft} selected={selected} onSelect={setSelected} onChange={change} status=""/></aside></div></div>;
}

