export type Element = {
  id: string; type: string; x: number; y: number; width: number; height: number;
  text?: string; color?: string; background?: string; border?: string;
  parent_id?: string | null; radius?: number; border_width?: number; font_size?: number; geometry?: string;
};
export type Layout = { version: number; background: string; viewport: { width: number; height: number }; elements: Element[]; limitations: string[] };

export function ElementEditor({ layout, selected, onSelect, onChange, status }: {
  layout: Layout; selected: string; onSelect: (id: string) => void;
  onChange: (patch: Partial<Element>) => void; status: string;
}) {
  const element = layout.elements.find(e => e.id === selected);
  const number = (label: string, key: keyof Element, value: number, min = 0, max = 10000) => <label>{label}<input aria-label={label} type="number" min={min} max={max} step="1" value={value} onChange={e => { const n = e.currentTarget.valueAsNumber; if (Number.isFinite(n)) onChange({ [key]: Math.max(min, Math.min(max, n)), ...(key === 'radius' ? { geometry: 'rounded-rectangle' } : {}) }); }} /></label>;
  const color = (label: string, key: keyof Element, value: string) => <label>{label}<input aria-label={label} type="color" value={value} onChange={e => onChange({ [key]: e.target.value })} /></label>;
  return <section className="editor panel"><div className="panel-heading"><h2><span>03</span> Edit elements</h2><span className="edit-status" role="status">{status}</span></div><div className="editor-body"><label className="element-selector">Selected element<select aria-label="Selected element" value={selected} onChange={e => onSelect(e.target.value)}><option value="">Choose an element</option>{layout.elements.map((e, i) => <option key={e.id} value={e.id}>{i+1}. {e.type}{e.text ? ` — ${e.text.slice(0, 40)}` : ''}</option>)}</select></label>{element ? <><div className="property-grid">{number('X position', 'x', element.x)}{number('Y position', 'y', element.y)}{number('Width', 'width', element.width, 1)}{number('Height', 'height', element.height, 1)}</div>{['text', 'button'].includes(element.type) && <><label>Text<input aria-label="Element text" value={element.text ?? ''} maxLength={10000} onChange={e => onChange({ text: e.target.value })} /></label><div className="property-grid">{number('Font size', 'font_size', element.font_size ?? (element.type === 'text' ? Math.round(element.height * .95) : 20), 1, 500)}{color('Text color', 'color', element.color ?? (element.type === 'button' ? '#ffffff' : '#172554'))}</div></>}{['container', 'button', 'input'].includes(element.type) && <div className="property-grid">{color('Fill color', 'background', element.background ?? '#ffffff')}{color('Border color', 'border', element.border ?? '#cbd5e1')}{number('Corner radius', 'radius', element.radius ?? 0, 0, 5000)}{number('Border width', 'border_width', element.border_width ?? 1, 0, 50)}</div>}{element.type === 'image' && <p className="editor-help">This graphic is an image crop. You can change its position and size.</p>}<p className="editor-help">Changes update the preview and both downloads automatically. Positions use the original screenshot’s pixels. Container changes do not move child elements.</p></> : <p className="editor-help">Choose from the list or click an element in the preview.</p>}</div></section>;
}
