import {useEffect,useRef,useState} from 'react';
import {examples,type Example} from './examples';
import {navigate,saveProject} from './projects';
import {notify} from './Notifications';
import type {Layout} from './ElementEditor';

export default function Examples(){
 const [category,setCategory]=useState('All'),[mode,setMode]=useState<'reference'|'draft'>('reference'),[divider,setDivider]=useState(50),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const controller=useRef<AbortController|null>(null);useEffect(()=>()=>controller.current?.abort(),[]);
 const opening=useRef(false),featured=examples[0],visible=examples.filter(e=>category==='All'||e.category===category);
 async function open(e:Example){if(opening.current)return;opening.current=true;const c=new AbortController();controller.current=c;setBusy(e.id);setError('');try{const [imageResponse,layoutResponse]=await Promise.all([fetch(e.file,{signal:c.signal}),fetch('/examples/'+e.id+'.json',{signal:c.signal})]);if(!imageResponse.ok||!layoutResponse.ok)throw Error('This example could not be loaded. Please try again.');const [blob,layout]=await Promise.all([imageResponse.blob(),layoutResponse.json() as Promise<Layout>]);const source=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result as string);r.onerror=()=>reject(Error('Could not read the example.'));r.readAsDataURL(blob);});const id=crypto.randomUUID();await saveProject({id,name:e.name,source,layout,original:layout,updatedAt:Date.now(),exampleId:e.id});if(c.signal.aborted)return;navigate('/editor/'+id);notify('Your own example copy is ready to edit.');}catch(e){if(c.signal.aborted)return;setError(e instanceof Error?e.message:'Could not open example.');}finally{opening.current=false;setBusy('');}}
 return <main className="page gallery-page"><header className="gallery-heading"><p className="eyebrow">THE SCREENWEAVE PLAYGROUND</p><h1>Start with a little<br/><em>possibility.</em></h1><p>Six starting points. Real reconstruction results.<br/>Pick a design, explore its layers, and make it yours.</p><span className="gallery-count">06 curated references <span>↘</span></span></header>
 {error&&<p className="error" role="alert">{error}</p>}<section className="gallery-featured" aria-labelledby="featured-title"><div className="featured-copy"><p className="eyebrow">01 / A GOOD PLACE TO START</p><h2 id="featured-title">One reference.<br/>A new first draft.</h2><p>Slide between the original and its actual reconstruction. Then step inside and try your first edit.</p><div className="gallery-tags"><span>Simple</span><span>Rounded controls</span></div><button className="primary" disabled={!!busy} onClick={()=>void open(featured)}>{busy===featured.id?'Opening…':'Open in editor'} <span aria-hidden="true">↗</span></button><small>A saved pipeline result, including its imperfections. Fresh reconstructions can differ.</small></div><div className="featured-visual"><div className="featured-labels"><span>Original</span><span>Reconstructed</span></div><div className="gallery-comparison" onPointerDown={e=>{if(e.button!==0)return;e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect();setDivider(Math.round(Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100))));}} onPointerMove={e=>{if(!e.currentTarget.hasPointerCapture(e.pointerId))return;const r=e.currentTarget.getBoundingClientRect();setDivider(Math.round(Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100))));}}><img src="/examples/rounded-draft.png" alt="Actual reconstructed rounded login screen"/><img className="gallery-original" src={featured.file} alt="Original rounded login reference" style={{clipPath:`inset(0 ${100-divider}% 0 0)`}}/><div className="gallery-divider" style={{left:divider+'%'}}><span>↔</span></div></div><label className="gallery-range">Compare original and draft<input type="range" aria-label="Featured comparison divider" min="0" max="100" value={divider} onChange={e=>setDivider(Number(e.target.value))}/></label></div></section>
 <section className="gallery-library" aria-labelledby="gallery-title"><div className="gallery-library-heading"><div><p className="eyebrow">FIND YOUR STARTING POINT</p><h2 id="gallery-title">A few ways to begin.</h2></div><div className="gallery-preview-mode" aria-label="Preview content">{(['reference','draft'] as const).map(m=><button key={m} aria-pressed={mode===m} onClick={()=>setMode(m)}>{m==='reference'?'References':'Actual drafts'}</button>)}</div></div><div className="gallery-filter-row"><div className="gallery-filters" aria-label="Filter examples">{['All','Forms','Dashboards','Cards','Images & text'].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}</button>)}</div><span role="status">{visible.length} {visible.length===1?'example':'examples'}</span></div><div className="gallery-grid">{visible.map((e)=><article className={'gallery-card tone-'+e.accent} key={e.id}><div className="gallery-card-preview"><span className="gallery-difficulty">{e.difficulty}</span><img loading="lazy" src={mode==='draft'?'/examples/'+e.id+'-draft.png':e.file} alt={e.name+(mode==='draft'?' actual reconstruction':' reference design')}/><span className="gallery-preview-caption">{mode==='draft'?'ACTUAL PIPELINE OUTPUT':'REFERENCE DESIGN'}</span></div><div className="gallery-card-copy"><p className="eyebrow">{e.category}</p><h3>{e.name}</h3><p>{e.description}</p><div className="gallery-tags">{e.tags.map(t=><span key={t}>{t}</span>)}</div><p className="gallery-review-note">{e.note}</p><div className="gallery-card-actions"><button disabled={!!busy} onClick={()=>void open(e)} aria-label={'Open '+e.name+' in editor'}>{busy===e.id?'Opening…':'Open in editor'} <span aria-hidden="true">↗</span></button><a href={'/new?example='+e.id}>Reconstruct again</a></div></div></article>)}</div></section>
 <section className="gallery-upload"><div><p className="eyebrow">YOUR IDEAS BELONG HERE, TOO</p><h2>Already have something in mind?</h2><p>Bring your own screenshot and start a fresh reconstruction.</p></div><a className="button primary" href="/new">Upload your screenshot ↗</a></section><p className="gallery-footnote">Original synthetic designs made for ScreenWeave. Each example opens as a separate project in this browser. Difficulty labels describe expected editing effort, not measured accuracy.</p></main>;
}
