export type Example={id:string;name:string;category:string;difficulty:string;file:string;description:string;tags:string[];note:string;task:string;accent:string};
export const examples:Example[]=[
 {id:'rounded',name:'Soft corners',category:'Forms',difficulty:'Simple',file:'/examples/rounded.png',description:'A familiar sign-in, with a softer edge.',tags:['Rounded controls','Typography'],note:'Check the curved icon and text alignment.',task:'Select “Welcome back” and make the heading your own.',accent:'sage'},
 {id:'pricing',name:'Room to grow',category:'Cards',difficulty:'Moderate',file:'/examples/pricing.png',description:'Two plans. A little space for big ideas.',tags:['Repeated cards','Buttons'],note:'Review card grouping and the price baselines.',task:'Change the Studio price, then adjust its button color.',accent:'cream'},
 {id:'product',name:'Everyday objects',category:'Images & text',difficulty:'Challenging',file:'/examples/product.png',description:'A small product story in warm, quiet colors.',tags:['Product layout','Gradients'],note:'The shaded illustration may need manual correction.',task:'Change the product name and inspect the illustration against the original.',accent:'sand'},
 {id:'dashboard',name:'The weekly picture',category:'Dashboards',difficulty:'Challenging',file:'/examples/dashboard.png',description:'Metrics and activity, all in one place.',tags:['Metric cards','Chart shapes'],note:'Chart bars are visual shapes, not a working chart.',task:'Edit a metric, then compare the chart bars with the reference.',accent:'sky'},
 {id:'profile',name:'Meet the maker',category:'Cards',difficulty:'Moderate',file:'/examples/profile.png',description:'A personal profile with a little personality.',tags:['Avatar','Nested layout'],note:'Review avatar edges and overlapping elements.',task:'Replace the name and biography with your own.',accent:'lavender'},
 {id:'banner',name:'A different perspective',category:'Images & text',difficulty:'Challenging',file:'/examples/banner.png',description:'Editorial lettering over a textured illustration.',tags:['Image text','Background cleanup'],note:'Text extraction may leave artifacts in the background.',task:'Select the banner image and try “Extract editable text”. Preview before applying.',accent:'forest'},
];
export const findExample=(id:string|null)=>examples.find(e=>e.id===id)??(id==='login'?{id:'login',name:'The essentials',file:'/examples/login.png'}:undefined);
