import {useEffect,useRef,useState} from 'react';
const steps=['Reference','Detect layers','Make an edit','Export code'];
export default function HeroDemo(){
 const [step,setStep]=useState(0),[playing,setPlaying]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches),[visible,setVisible]=useState(true);
 const root=useRef<HTMLDivElement>(null);
 useEffect(()=>{const media=window.matchMedia('(prefers-reduced-motion: reduce)');const change=()=>{if(media.matches)setPlaying(false);};media.addEventListener('change',change);const observer=new IntersectionObserver(([entry])=>setVisible(entry.isIntersecting));if(root.current)observer.observe(root.current);return()=>{observer.disconnect();media.removeEventListener('change',change);};},[]);
 useEffect(()=>{if(!playing||!visible)return;const timer=setInterval(()=>{if(document.hidden)return;setStep(step+1);if(step>=2)setPlaying(false);},2600);return()=>clearInterval(timer);},[playing,visible,step]);
 return <div className="hero-demo-wrap" ref={root}><div className={'hero-demo animated-demo demo-step-'+step+(playing?'':' demo-paused')} aria-label="Illustrated screenshot to editable website workflow"><div className="demo-chrome"><i/><i/><i/><span>SCREENWEAVE / {steps[step].toUpperCase()}</span></div><div className="demo-grid"><div className="demo-layers"><small>{step===0?'REFERENCE':'LAYERS'}</small><div className="demo-layer-items" style={{opacity:step===0?.3:1}}><p>▢ Card</p><p className="demo-selected">T {step>=2?'Make it yours':'Welcome back'}</p><p>▢ Email field</p><p>▢ Continue</p></div><span className="demo-stage-note">{['Start with a screenshot','Find the structure','Refine the details','Take your next step'][step]}</span></div><div className="demo-canvas"><div className="demo-login"><span className="demo-logo">w.</span><h3>{step>=2?'Make it yours.':'Welcome back.'}</h3><p>A little less setup. A little more creating.</p><div className="fake-input">you@example.com</div><div className="fake-input">••••••••••</div><div className="fake-button">{step>=2?'Let’s begin →':'Continue →'}</div></div>{step===1&&<div className="hero-scan" aria-hidden="true"/>}{step===2&&<span className="demo-cursor" aria-hidden="true">↖ Edit the heading</span>}{step===3&&<div className="hero-export-preview"><span className="hero-export-check">✓</span><strong>Your design. Your code.</strong><code>{'<ReconstructedButton\n  text="Let’s begin"\n/>'}</code><div><span>HTML / CSS</span><span>React</span><span>Tailwind</span></div><small>Illustrative export preview</small></div>}</div></div><div className="demo-bottom"><span>{['Bring a reference','Detect editable elements','Change text, colors and layout','Continue in your own codebase'][step]}</span><strong>{String(step+1).padStart(2,'0')} / 04</strong></div></div><div className="hero-demo-controls"><div className="hero-demo-steps" aria-label="Demo stages">{steps.map((label,i)=><button key={label} aria-label={'Show '+label.toLowerCase()+' stage'} aria-pressed={step===i} onClick={()=>{setStep(i);setPlaying(false);}}><span>{i+1}</span>{label}</button>)}</div><button className="hero-motion-button" onClick={()=>{if(step===3){setStep(0);setPlaying(true);}else setPlaying(!playing);}} aria-label={playing?'Pause hero demo':step===3?'Replay hero demo':'Play hero demo'}>{playing?'Ⅱ Pause':step===3?'↻ Replay':'▷ Play'}</button></div><p className="hero-demo-caption">Illustrated workflow · See real results in the examples gallery.</p></div>;
}
