import {useEffect,useRef,useState} from 'react';
import type {Element,Layout} from './ElementEditor';
import {apiRequest,type Result} from './projects';
export default function ImageTextExtraction({image,onApply}:{image:Element;onApply:(layout:Layout)=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null);
 const controller=useRef<AbortController|null>(null),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>()=>controller.current?.abort(),[]);
 useEffect(()=>{if(result)dialog.current?.showModal();},[result]);
 async function extract(){const c=new AbortController();controller.current=c;setBusy(true);setError('');const timer=setTimeout(()=>c.abort(),180000);try{const blob=await(await fetch(image.src!)).blob();const next=await apiRequest('/extract-text',blob,'image/png',c.signal);if(!c.signal.aborted)setResult(next);}catch(e){if(!c.signal.aborted)setError(e instanceof Error?e.message:'Extraction failed.');else setError('Extraction cancelled or timed out.');}finally{clearTimeout(timer);setBusy(false);}}
 const doc=result?.html.replace('<link rel="stylesheet" href="styles.css">',`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:;"><style>${result.css}</style>`);
 return <section className="image-text-tools"><h3>Editable image text</h3><p>Separate lettering from this image. Preview the background cleanup before applying.</p><button disabled={busy} onClick={()=>void extract()}>{busy?'Extracting text…':'Extract editable text'}</button>{busy&&<button onClick={()=>controller.current?.abort()}>Cancel extraction</button>}{error&&<p role="alert">{error}</p>}{result&&<dialog ref={dialog} className="extraction-dialog" aria-labelledby="extraction-title" onCancel={()=>setResult(null)}><h2 id="extraction-title">Review extracted text</h2><p>{result.layout.elements.length-1} editable text {result.layout.elements.length===2?'layer':'layers'}. Cleanup can leave artifacts; compare both images before applying.</p><div className="extraction-previews"><figure><figcaption>Original</figcaption><img src={image.src} alt="Original image before text extraction"/></figure><figure><figcaption>Cleaned background + editable text</figcaption><div className="extraction-frame"><iframe title="Editable text preview" sandbox="" srcDoc={doc} style={{width:result.layout.viewport.width,height:result.layout.viewport.height}}/></div></figure></div><div className="actions"><button className="primary" onClick={()=>{onApply(result.layout);setResult(null);}}>Apply extracted text</button><button onClick={()=>setResult(null)}>Cancel</button></div></dialog>}</section>;
}
