const {chromium}=require(process.argv[2]||'playwright');const fs=require('node:fs'),path=require('node:path');
fs.mkdirSync('reports/gallery',{recursive:true});
const css=`*{box-sizing:border-box}body{margin:0;background:#f4f6f1;color:#193b33;font-family:Arial,sans-serif;padding:42px}h1{font-size:34px;margin:14px 0}h2{font-size:24px;margin:0 0 12px}p{font-size:16px;line-height:1.6;color:#5b7067}small{font-size:13px;letter-spacing:2px;color:#5b7067}.row{display:flex;gap:22px}.card{background:white;border:1px solid #cad7c8;border-radius:20px;padding:26px;flex:1}button{background:#244d3e;color:white;border:0;border-radius:24px;padding:15px 24px;font:16px Arial}strong{display:block;font-size:40px;margin:24px 0}.muted{color:#64776b} .line{height:1px;background:#e3e9dd;margin:18px 0}`;
const examples={
pricing:`<small>PLANS THAT GROW WITH YOU</small><h1>A little space for big ideas.</h1><p>Choose the workspace that suits your next chapter.</p><div class="row" style="margin-top:32px"><section class="card"><h2>Personal</h2><p>A home for your first projects.</p><strong>$0 <span style="font-size:15px">/ month</span></strong><div class="line"></div><p>3 active projects<br>Community templates<br>Basic exports</p><button>Start creating</button></section><section class="card" style="background:#e6efd5;border-color:#9db787"><h2>Studio</h2><p>More room to experiment.</p><strong>$12 <span style="font-size:15px">/ month</span></strong><div class="line"></div><p>Unlimited projects<br>Shared libraries<br>Advanced exports</p><button>Choose Studio</button></section></div>`,
product:`<small>OBJECTS FOR EVERYDAY LIVING</small><div class="row" style="margin-top:30px"><div style="width:390px;height:420px;background:#e8d9c3;border-radius:24px;display:grid;place-items:center"><div style="width:190px;height:230px;border-radius:20px 20px 65px 65px;background:linear-gradient(110deg,#68876a,#c5d6a5 48%,#506b55);box-shadow:16px 24px 35px #725d3933"></div></div><div style="flex:1;padding:24px"><small>THE SLOW MORNING COLLECTION</small><h1>The everyday cup.</h1><p>A quiet companion for your morning ritual. Glazed stoneware in soft sage.</p><strong>$28</strong><p>Color: Sage green</p><button>Add to bag</button></div></div>`,
dashboard:`<small>WORKSPACE / OVERVIEW</small><h1>A good week, in focus.</h1><p>Your studio activity at a glance.</p><div class="row"><div class="card"><p>Projects completed</p><strong>24</strong></div><div class="card"><p>Hours saved</p><strong>18.5</strong></div><div class="card"><p>Active collaborators</p><strong>8</strong></div></div><section class="card" style="margin-top:22px"><h2>Weekly activity</h2><div style="display:flex;height:145px;gap:28px;align-items:flex-end;padding:15px 24px">${[45,80,58,110,95,130,75].map(h=>`<div style="height:${h}px;flex:1;background:#91ae70;border-radius:8px 8px 0 0"></div>`).join('')}</div><p>Mon　　Tue　　Wed　　Thu　　Fri　　Sat　　Sun</p></section>`,
profile:`<div class="card" style="width:620px;margin:15px auto;padding:40px"><div style="height:100px;border-radius:15px;background:#dde9ce"></div><div style="width:90px;height:90px;background:#244d3e;color:#edf4e5;border:6px solid white;border-radius:50%;display:grid;place-items:center;font-size:30px;margin-top:-36px;position:relative">AR</div><small>PRODUCT DESIGNER</small><h1>Alex Rivera</h1><p>Making useful things feel simple.<br>Based in a small studio, working everywhere.</p><div class="line"></div><div class="row"><div style="flex:1"><h2>32</h2><p>Projects</p></div><div style="flex:1"><h2>1.2k</h2><p>Followers</p></div><button style="height:48px;margin-top:14px">Follow Alex</button></div></div>`,
banner:`<small>CREATIVE FIELD NOTES</small><div style="margin-top:25px;position:relative;height:380px;border-radius:22px;overflow:hidden;background:#21483c"><svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%"><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#1c5145"/><stop offset="1" stop-color="#bcaa71"/></linearGradient><filter id="n"><feTurbulence type="fractalNoise" baseFrequency=".035" numOctaves="3" seed="12"/><feBlend in="SourceGraphic" mode="soft-light"/></filter></defs><rect width="100%" height="100%" fill="url(#g)"/><rect width="100%" height="100%" fill="url(#g)" opacity=".35" filter="url(#n)"/></svg><div style="position:absolute;top:70px;left:48px;color:white"><small style="color:white">MAKE ROOM FOR CURIOSITY</small><h1 style="font-size:44px;width:490px">Explore a different perspective.</h1><p style="color:#f1f1de">A collection of ideas for your next chapter.</p><button style="background:white;color:#21483c">Read the journal</button></div></div><p>Try extracting the lettering from the detected image layer.</p>`
};
(async()=>{const b=await chromium.launch({channel:'msedge',headless:true});try{const p=await b.newPage({viewport:{width:900,height:650},deviceScaleFactor:1});for(const [id,body] of Object.entries(examples)){await p.setContent('<!doctype html><html><head><style>'+css+'</style></head><body>'+body+'</body></html>');await p.screenshot({path:path.join('frontend/public/examples',id+'.png'),fullPage:true});fs.writeFileSync(path.join('reports/gallery',id+'-source.html'),await p.content());}}finally{await b.close()}})().catch(e=>{console.error(e);process.exit(1)});
